sudo: required

services:
  - docker

language: go
go:
  - tip

before_install:
  - sudo apt-get -qq update
  - docker pull fedora
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh
  - cd $GOPATH/src/github.com/mh-cbon/
  - git clone https://github.com/mh-cbon/changelog.git
  - cd changelog
  - glide install
  - go build -o ../go-bin-rpm/changelog main.go
  - cd $GOPATH/src/github.com/mh-cbon/go-bin-rpm
  - glide install
  - mkdir -p build/{386,amd64}
  - go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o go-bin-rpm main.go
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/go-bin-rpm main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/go-bin-rpm main.go

install:
  - docker run -v $PWD:/docker  fedora /bin/sh -c "cd /docker && sh ./docker.sh ${TRAVIS_TAG}"
  - ls -al

script: echo "pass"

deploy:
  provider: releases
  api_key:
    secure: sQ4odOUxKJOpeEaKorSaKPKdJelqPUTNrTAmhXER3kFGxCZqEGmPOr3Ibb+TiiPVRWhMTj08EbqVtdA0hJwHw5/FeuVZj58QOwUM5SmzKuArDaokWUKKrXwcdg1UDGBEtfkK4goFEOnMTF1PxticEBvS5NPvHp+GKfdLvSh03Wy21rCHRKuVS129e7rxbrNCOaVl2OzmOchTEIBetASUwBHVEDkm9kkIsd+LASSOCzJ4dCjAX8fjPckgTiOmiVftmZcnAKbFCNgNKiyuVUYkAF4NxjJ2SHhoOgsIUMamMWfOtRkCAbB2S4rxeefAz4R9Pof3u7vQziv6gBmpHw1QjzJJevjywqpwG5DLkGsLxWSZNzpSeQSubAO7B4KVG4qKwjOqs2EqT8ritd8nZhmpt2qC99z/cDjnDLVpx92gNUOFfbvVWaqvHQ9dCJTidbNzKya4gWjy5HjL2jJfmeZNoCtU+B2uN2o7esgLgPnQmeN4tdnlmc3wkNuFmoL1T57AEqOU6z3yk/Knh8qJELJJsaLYY4uz1RY6JKLktvyhaB4i+zCv5hvhXpYEIZND1UKZiRNh57jYAIq6fxKL9fbZpnw9TFor6vtoDAaXdxf2C9gGt9pR4SxjODicR/TVEaGZNTAOatF1CBXo29/+Sf8tPo5HrJKxPZtAb7vYIF1UYBk=
  file:
    - go-bin-rpm-386.rpm
    - go-bin-rpm-amd64.rpm
  skip_cleanup: true
  on:
tags: true
