sudo: required

services:
  - docker

language: go
go:
  - tip

before_install:
  - sudo apt-get -qq update
  - docker pull fedora
  - docker run fedora /bin/sh -c "pwd & ls -al"
  - docker run fedora /bin/sh -c "pwd & ls -al"

install:
  - curl https://glide.sh/get | sh
  - glide install

script: echo "pass"
