sudo: required

services:
  - docker

language: go
go:
  - tip

before_install:
  - sudo apt-get -qq update
  - docker pull fedora
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh
  - cd $GOPATH/src/github.com/mh-cbon/go-bin-rpm
  - glide install
  - mkdir -p build/{386,amd64}
  - go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o go-bin-rpm main.go
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/go-bin-rpm main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/go-bin-rpm main.go

install:
  - docker run -v $PWD:/docker  fedora /bin/sh -c "sh ./docker.sh"
  - ls -al

script: echo "pass"
